language: php
sudo: false

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

jobs:
  include:
    - stage: test
      name: "Symfony +2.5"
      script: composer require symfony/event-dispatcher:~2.5.0 && php bin/phpunit
    - name: "Symfony +3.0"
      script: composer require symfony/event-dispatcher:~3.0.0 && php bin/phpunit
    - name: "Symfony +4.0"
      script: composer require symfony/event-dispatcher:~4.0.0 && php bin/phpunit
    - name: "Symfony +5.0"
      script: composer require symfony/event-dispatcher:~5.0.0 && php bin/phpunit

script:
    - phpenv config-rm xdebug.ini
    - composer install
    - php bin/build.sh

env:
  global:
    - XDEBUG_MODE=off
