name: PHP Domain event

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
        dispatcher-version: ['2.5.0', '3.0.0', '4.0.0', '5.0.0', '6.0.0']
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress && composer require symfony/event-dispatcher:~{{ dispatcher-version }}

    - name: PHPUnit
      run: bin/phpunit

    - name: PHP code sniffer
      run: bin/phpcs

    - name: PHPStan
      run: bin/phpstan
