name: PHP Domain event

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PHP-7-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Event dispatcher 2.5.0
      run: composer require --dev symfony/event-dispatcher:~2.5.0 -W
    - name: Event dispatcher 3.0.0
      run: composer require --dev symfony/event-dispatcher:~3.0.0 -W
    - name: Event dispatcher 4.0.0
      run: composer require --dev symfony/event-dispatcher:~4.0.0 -W

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: PHPUnit
      run: bin/phpunit

    - name: PHP code sniffer
      run: bin/phpcs

    - name: PHPStan
      run: bin/phpstan

  PHP-7-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Event dispatcher 2.5.0
        run: composer require --dev symfony/event-dispatcher:~2.5.0 -W
      - name: Event dispatcher 3.0.0
        run: composer require --dev symfony/event-dispatcher:~3.0.0 -W
      - name: Event dispatcher 4.0.0
        run: composer require --dev symfony/event-dispatcher:~4.0.0 -W
      - name: Event dispatcher 5.0.0
        run: composer require --dev symfony/event-dispatcher:~5.0.0 -W

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: PHPUnit
        run: bin/phpunit

      - name: PHP code sniffer
        run: bin/phpcs

      - name: PHPStan
        run: bin/phpstan

  PHP-7-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Event dispatcher 2.5.0
        run: composer require --dev symfony/event-dispatcher:~2.5.0 -W
      - name: Event dispatcher 3.0.0
        run: composer require --dev symfony/event-dispatcher:~3.0.0 -W
      - name: Event dispatcher 4.0.0
        run: composer require --dev symfony/event-dispatcher:~4.0.0 -W
      - name: Event dispatcher 5.0.0
        run: composer require --dev symfony/event-dispatcher:~5.0.0 -W

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: PHPUnit
        run: bin/phpunit

      - name: PHP code sniffer
        run: bin/phpcs

      - name: PHPStan
        run: bin/phpstan

  PHP-7-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Event dispatcher 2.5.0
        run: composer require --dev symfony/event-dispatcher:~2.5.0 -W
      - name: Event dispatcher 3.0.0
        run: composer require --dev symfony/event-dispatcher:~3.0.0 -W
      - name: Event dispatcher 4.0.0
        run: composer require --dev symfony/event-dispatcher:~4.0.0 -W
      - name: Event dispatcher 5.0.0
        run: composer require --dev symfony/event-dispatcher:~5.0.0 -W

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: PHPUnit
        run: bin/phpunit

      - name: PHP code sniffer
        run: bin/phpcs

      - name: PHPStan
        run: bin/phpstan

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.0', '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: PHPUnit
        run: bin/phpunit

      - name: PHP code sniffer
        run: bin/phpcs

      - name: PHPStan
        run: bin/phpstan
